-- drizzle/migrations/0003_add_lesson_progress.sql
ALTER TABLE "user_progress"
ADD COLUMN IF NOT EXISTS "lesson_id" INTEGER,
ADD COLUMN IF NOT EXISTS "course_id" INTEGER,
ADD COLUMN IF NOT EXISTS "completed" BOOLEAN,
ADD COLUMN IF NOT EXISTS "score" INTEGER,
ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "last_updated" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;